name: dart_advent
description: Advent of Code 2022
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  uuid: ^3.0.6
  matrices: ^1.0.9
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
